# Generated by Django 4.2.2 on 2024-06-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAssignmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_details', models.CharField(default='', max_length=1024)),
                ('ip_address', models.CharField(default='000.000.000.000', max_length=15, null=True)),
                ('remarks', models.CharField(default='', max_length=1024)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_assigend_to', to='masters.employee')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_section', to='masters.section')),
            ],
        ),
    ]
