# Generated by Django 4.2.2 on 2024-06-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemassignmentdetails',
            name='system_details',
        ),
        migrations.AlterField(
            model_name='systemassignmentdetails',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_assigend_to', to='masters.employee', unique=True),
        ),
        migrations.AlterField(
            model_name='systemassignmentdetails',
            name='ip_address',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AllotedDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_details', models.CharField(default='', max_length=1024)),
                ('remarks', models.CharField(default='', max_length=1024)),
                ('system_assignment_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_assigend_to', to='operation.systemassignmentdetails')),
            ],
        ),
    ]
