# Generated by Django 4.2.2 on 2024-06-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('operation', '0002_remove_systemassignmentdetails_system_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemassignmentdetails',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_assigend_to', to='masters.employee'),
        ),
    ]
